numbers = [1,3,5,3,1,5,9]
# numbers.append(9)
# print(numbers)
# numbers.extend([8,4,2])
# print(numbers)
# numbers.clear()
# print(numbers)
# print(numbers.index(5))
# numbers.insert(0,9)
# print(numbers)
# numbers.remove(1)
# print(numbers)
# numbers.pop()
# print(numbers)
# print(numbers.count('1'))
# numbers.sort()
# print(numbers)
# numbers.sort(reverse=True)
# print(numbers)
# numbers.reverse()
# print(numbers)
# numbers.pop(1)
numbers.remove(5)
print(numbers)
