from collections import deque
d = deque([5,7,1,2])
# d.append(9)
# print(d)
# d.appendleft(23)
# print(d)
# d.pop()
# print(d)
# d.popleft()
# print(d)
# d.extend([8,5])
# print(d)
# d.extendleft([8,5])
# print(d)
d.rotate(1)
print(d)