import math
# r = math.sqrt(25)
# print(r)
# r=math.fsum([4,3,2,6])
# print(r)
# r=math.ceil(2.3)
# print(r)
# r=math.floor(2.3)
# print(r)
# r=math.factorial(4)
# print(r)
# r=math.lcm(2,8)
# print(r)
# r=math.pow(4,2)
# print(r)
# r=math.trunc(45.3)
# print(r)
# r=math.prod([3,2,4])
# print(r)
# r=math.gcd(2,8)
# print(r)
r=math.fmod(3,2)
print(r)
