import numpy as np
arr = np.array([6,8,4,3,2])
# print(arr)
# print(arr[0])
arr1 = np.array([[6,8,4],[9,1,5]])
# print(arr1)
# print(arr1[0][1])
# print(arr.ndim)
# print(arr1.ndim)
# print(arr.shape)
# print(arr1.shape)
print(arr.dtype)
print(arr.size)
print(arr1.size)
